# Generated by Django 4.2 on 2023-04-29 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_userfollowings_follower_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserFollowings",
            new_name="UserFollowing",
        ),
    ]
